### ISSUE TITLE
More python versions

### ISSUE THREAD

**Issue by ChuckMoe** [Midnighter/fastapi-base#2]
Hey there!
Your project is just what I was searching for! I would like to to use newer versions of python however. Just wanted to ask if I can open a PR for it here or if you would rather like me to fork your repo?
Cheers
Moe

**Comment by Midnighter** [comment]
Hey,

Glad you find it useful! I must admit that I don't use it any longer myself. I'm happy to receive PRs, though, so others may use it. If you end up forking it so you have more control I won't be cross 😉 Up to you.

**Comment by ChuckMoe** [comment]
Just like your repo title say, I only want to use it as base, so opening PRs is just fine for me at the moment :)

**Comment by Midnighter** [comment]
Cool, I don't know what you're planning to use but I'd probably drop the alpine-based images entirely. The Python-slim images are very small now and much more convenient.

**Comment by ChuckMoe** [comment]
I am completely fine with slim-buster version
